const KEY='s2p_state', state=()=>JSON.parse(localStorage.getItem(KEY)||'{}'), put=x=>localStorage.setItem(KEY,JSON.stringify(x)), esc=x=>String(x||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const api=async(path,options={})=>{let s=state(),r=await fetch(path,{...options,headers:{'Content-Type':'application/json','X-User-Id':s.user?.id||'',...(options.headers||{})}}),d=await r.json();if(!r.ok)throw Error(d.error||'Something went wrong.');return d};
document.querySelectorAll('[data-progress]').forEach(p=>p.innerHTML=Array.from({length:8},(_,i)=>`<span class="${i<+p.dataset.progress?'active':''}"></span>`).join(''));const deviceStyle=document.createElement('style');deviceStyle.textContent='@media(max-width:700px){nav{height:auto;min-height:64px;padding:10px 16px;gap:10px}nav>div{gap:10px;flex-wrap:wrap;justify-content:flex-end}nav>div>a:not(.button){display:inline!important;font-size:11px}.brand{font-size:14px}.brand i{width:24px;height:24px}.idea p{font-size:14px!important;line-height:1.75}.idea h4{font-size:13px!important}.idea h2{font-size:24px!important}}.idea p{font-size:13px}.idea h4{font-size:12px}';document.head.append(deviceStyle);
document.querySelectorAll('nav>div').forEach(nav=>{if(state().user)nav.innerHTML='<a href="upload.html">New upload</a><a href="history.html">My history</a><button class="link-btn" onclick="logout()">Log out</button>'});
async function logout(){try{await api('/api/auth/logout',{method:'POST'})}finally{let s=state();delete s.user;put(s);location='index.html'}}
async function signUp(){let name=nameInput.value.trim(),email=emailInput.value.trim(),password=passwordInput.value;try{let d=await api('/api/auth/signup',{method:'POST',body:JSON.stringify({name,email,password})});let s=state();s.user=d.user;put(s);location='upload.html'}catch(e){error.textContent=e.message}}
async function logIn(){try{let d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:emailInput.value.trim(),password:passwordInput.value})});let s=state();s.user=d.user;put(s);location='upload.html'}catch(e){error.textContent=e.message}}
function requireUser(){if(!state().user){location='login.html';return false}return true}
function selectFile(f){if(!f)return;if(f.size>15*1024*1024)return error.textContent='Use a file smaller than 15 MB.';window.syllabusFile=f;fileName.textContent=f.name}
function sampleSyllabus(){window.syllabusFile=new File(['UNIT I: Introduction to Data Structures\nArrays, Linked Lists and Stacks\nUNIT II: Trees and Graphs\nBinary Trees, Traversal, Shortest Path Algorithms\nUNIT III: Hashing and Dynamic Programming\nHash Tables, Memoization and Optimization'],'sample-syllabus.txt',{type:'text/plain'});fileName.textContent='sample-syllabus.txt'}
async function extractSyllabus(){if(!window.syllabusFile){error.textContent='Choose a file or use the sample syllabus.';return}error.textContent='Reading file…';try{let text=await textFromFile(window.syllabusFile);error.textContent='Gemini is extracting chapters and topics…';let d=await api('/api/analyze-syllabus',{method:'POST',body:JSON.stringify({text})}),s=state();s.chapters=d.chapters;s.fileName=window.syllabusFile.name;put(s);location='chapters.html'}catch(e){error.textContent=e.message}}
async function textFromFile(f){let ext=f.name.split('.').pop().toLowerCase();if(ext==='txt')return f.text();if(ext==='docx')return(await mammoth.extractRawText({arrayBuffer:await f.arrayBuffer()})).value;if(ext==='pdf'){let m=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');m.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';let pdf=await m.getDocument({data:await f.arrayBuffer()}).promise,t='';for(let i=1;i<=pdf.numPages;i++){let c=await(await pdf.getPage(i)).getTextContent();t+=c.items.map(x=>x.str).join(' ')+'\n'}return t}if(/^image\//.test(f.type))return(await Tesseract.recognize(f,'eng')).data.text;throw Error('Use PDF, DOCX, TXT, PNG, JPG, or WEBP.')}
function renderChapters(){if(!requireUser())return;let s=state();if(!s.chapters)return location='upload.html';chapters.innerHTML=s.chapters.map((c,i)=>`<button class="select-card chapter-card" onclick="chooseChapter(${i})"><span>${esc(c.name)}<small>${c.topics.length} Gemini-extracted topics</small></span><b>0${i+1} →</b></button>`).join('')}
function chooseChapter(i){let s=state();s.chapter=i;delete s.topic;put(s);location='topics.html'}
function renderTopics(){if(!requireUser())return;let s=state(),c=s.chapters?.[s.chapter];if(!c)return location='chapters.html';selectedChapter.textContent=`CHAPTER · ${c.name}`;topics.innerHTML=c.topics.map((t,i)=>`<button class="select-card" onclick="topicPopup(${i})">${esc(t.name)}<small>Gemini difficulty · ${esc(t.difficulty)}</small></button>`).join('')}
function topicPopup(i){let s=state();s.topic=i;put(s);document.getElementById('interestModal').classList.remove('hidden')}
function pickInterest(v){let s=state();s.interest=v;put(s);document.querySelectorAll('[data-interest]').forEach(b=>b.classList.toggle('selected',b.dataset.interest===v))}
function nextDifficulty(){if(!state().interest)return modalError.textContent='Choose an interest or hobby first.';location='difficulty.html'}
function renderDifficulty(){if(!requireUser())return;let s=state();if(!s.interest)return location='topics.html';difficultySummary.textContent=`YOUR INTEREST · ${s.interest}`;levels.innerHTML=['Beginner','Intermediate','Advanced'].map(v=>`<button class="select-card ${s.level===v?'selected':''}" onclick="pickLevel('${v}')">${v}<small>${v==='Beginner'?'A focused build with clear milestones':v==='Intermediate'?'A portfolio-ready feature set':'A deeper technical challenge'}</small></button>`).join('')}
function pickLevel(v){let s=state();s.level=v;put(s);renderDifficulty()}
async function generateIdeas(){let s=state();if(!s.level)return difficultyError.textContent='Choose your desired project level.';let topic=s.chapters[s.chapter].topics[s.topic];difficultyError.textContent='Gemini 2.5 Flash is creating your ideas…';try{let d=await api('/api/generate-projects',{method:'POST',body:JSON.stringify({chapter:s.chapters[s.chapter].name,topic:topic.name,topicDifficulty:topic.difficulty,interest:s.interest,level:s.level})});s.ideas=d.ideas;put(s);await api('/api/history',{method:'POST',body:JSON.stringify({topic:topic.name,interest:s.interest,level:s.level,ideas:s.ideas})});s.historySaved=true;put(s);location='results.html'}catch(e){difficultyError.textContent=e.message}}
function renderResults(){if(!requireUser())return;let s=state();if(!s.ideas)return location='difficulty.html';let topic=s.chapters[s.chapter].topics[s.topic];projectSummary.textContent=`${s.chapters[s.chapter].name} · ${topic.name} · ${s.interest} · ${s.level}`;ideas.innerHTML=s.ideas.map((p,i)=>`<article class="idea"><span class="label">0${i+1} · ${i?'ALTERNATIVE IDEA':'BEST MATCH'}</span><h2>${esc(p.title)}</h2><h4>What is this project?</h4><p>${esc(p.explanation)}</p><h4>Real-time applications</h4><p>${esc(p.realWorldApplication)}</p><h4>Recommended tech stack</h4><div class="tech">${p.techStack.map(x=>`<span>${esc(x)}</span>`).join('')}</div></article>`).join('')}
async function saveIdeas(){let s=state(),topic=s.chapters[s.chapter].topics[s.topic];try{await api('/api/history',{method:'POST',body:JSON.stringify({topic:topic.name,interest:s.interest,level:s.level,ideas:s.ideas})});saved.textContent='Saved in your project history.'}catch(e){saved.textContent=e.message}}
async function downloadPDF(){let s=state(),topic=s.chapters[s.chapter].topics[s.topic];try{let response=await fetch('/api/export-pdf',{method:'POST',headers:{'Content-Type':'application/json','X-User-Id':s.user?.id||''},body:JSON.stringify({topic:topic.name,interest:s.interest,level:s.level,ideas:s.ideas})});if(!response.ok){let data=await response.json();throw Error(data.error||'Could not create the PDF.')}let blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='gemini-project-ideas.pdf';document.body.append(link);link.click();link.remove();URL.revokeObjectURL(url)}catch(e){alert(e.message)}}
function printProjectBrief(){let s=state(),cards=s.ideas.map((p,i)=>`<section><h2>${i+1}. ${esc(p.title)}</h2><h3>What is this project?</h3><p>${esc(p.explanation)}</p><h3>Real-time applications</h3><p>${esc(p.realWorldApplication)}</p><h3>Recommended tech stack</h3><p>${p.techStack.map(esc).join(' · ')}</p></section>`).join(''),w=window.open('','_blank');if(!w)return alert('Please allow pop-ups to export your PDF.');w.document.write(`<html><head><title>Gemini Project Ideas</title><style>body{font-family:Arial;max-width:760px;margin:45px auto;line-height:1.6;color:#173437}section{border:1px solid #d9e2d9;border-radius:12px;padding:18px;margin:15px 0}h1{font-size:28px}h2{font-size:20px}h3{font-size:12px;text-transform:uppercase;color:#468568;margin-bottom:0}p{font-size:13px}</style></head><body><h1>Syllabus2Project — Gemini Ideas</h1>${cards}<script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
async function renderHistory(){if(!requireUser())return;try{let d=await api('/api/history'),el=document.getElementById('history');el.innerHTML=d.items.length?d.items.map(x=>`<article class="history-item"><div><h3>${esc(x.ideas[0].title)}</h3><p>${esc(x.topic)} · ${esc(x.interest)} · ${esc(x.level)}</p></div><div><span>${new Date(x.created_at).toLocaleDateString()}</span><button class="link-btn danger" onclick="deleteHistory(${x.id})">Delete</button></div></article>`).join(''):`<div class="history-empty"><h2>No saved projects yet.</h2><p>Your Gemini recommendations will appear here.</p><a class="button" href="upload.html">Upload a syllabus →</a></div>`}catch(e){history.innerHTML=`<p class="error">${esc(e.message)}</p>`}}
async function deleteHistory(id){if(!confirm('Delete this saved project?'))return;try{await api('/api/history/'+id,{method:'DELETE'});renderHistory()}catch(e){alert(e.message)}}
