const app={stage:1,user:JSON.parse(localStorage.getItem('s2p_user')||'null'),file:null,rawText:'',chapters:[],chapter:'',topic:'',interest:'',level:'',projects:[]};
const content=document.getElementById('wizardContent');
const stages=['Account','Upload','Read','Chapters','Topics','Interest','Level','Generate','Save','Export'];
const esc=v=>String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function openAuth(){app.stage=1;document.getElementById('wizard').classList.remove('hidden');render()}
function startJourney(){app.stage=app.user?2:1;document.getElementById('wizard').classList.remove('hidden');render()}
function closeWizard(){document.getElementById('wizard').classList.add('hidden')}
function go(n){app.stage=n;render()}
function render(){document.getElementById('wizardLabel').textContent=`STEP ${app.stage} OF 10 · ${stages[app.stage-1].toUpperCase()}`;document.getElementById('wizardProgress').innerHTML=stages.map((_,i)=>`<span class="${i<app.stage?'active':''}"></span>`).join('');({1:account,2:upload,3:reading,4:chooseChapter,5:chooseTopic,6:chooseInterest,7:chooseLevel,8:generating,9:saveIdeas,10:exportIdeas})[app.stage]()}
function account(){content.innerHTML=`<h2>${app.user?`Welcome back, ${esc(app.user.name)}.`:'Start your project journey.'}</h2><p>${app.user?'Your account is saved locally in this browser. Continue to upload your syllabus.':'Create a free student account to save recommendations and export them later.'}</p>${app.user?`<button class="primary next" onclick="go(2)">Continue <span>→</span></button>`:`<div class="auth-grid"><label class="form-field"><span>Full name</span><input id="userName" placeholder="Aarav Sharma"></label><label class="form-field"><span>Email address</span><input id="userEmail" type="email" placeholder="you@college.edu"></label></div><div class="form-message" id="formMessage"></div><button class="primary next" onclick="createAccount()">Create account <span>→</span></button>`}`}
function createAccount(){const name=document.getElementById('userName').value.trim(),email=document.getElementById('userEmail').value.trim();if(!name||!/^\S+@\S+\.\S+$/.test(email)){document.getElementById('formMessage').textContent='Enter your name and a valid email address.';return}app.user={name,email};localStorage.setItem('s2p_user',JSON.stringify(app.user));go(2)}
function upload(){content.innerHTML=`<h2>Upload your syllabus.</h2><p>We can read <b>PDF, DOCX, TXT, PNG, JPG, and WEBP</b> files. Image files are scanned with OCR to find topics.</p><label class="dropzone"><input type="file" accept=".pdf,.docx,.txt,image/png,image/jpeg,image/webp" onchange="receiveFile(this.files[0])"><div class="upload-circle">↑</div><b>${app.file?esc(app.file.name):'Choose a syllabus file'}</b><span>${app.file?'Ready to analyze':'PDF, DOCX, TXT, PNG, JPG, or WEBP · up to 15MB'}</span></label><button class="secondary" onclick="useSample()">Use a sample Data Structures syllabus</button><button class="primary next" onclick="beginReading()" ${app.file?'':'disabled'}>Analyze syllabus <span>→</span></button>`}
function receiveFile(f){if(!f)return;if(f.size>15*1024*1024){alert('Please choose a file smaller than 15 MB.');return}app.file=f;render()}
function useSample(){app.file=new File(['UNIT I: Introduction to Data Structures\nArrays, Linked Lists and Stacks\nUNIT II: Trees and Graphs\nBinary Trees, Traversal, Shortest Path Algorithms\nUNIT III: Hashing and Dynamic Programming\nHash Tables, Memoization and Optimization'],'data-structures-syllabus.txt',{type:'text/plain'});render()}
function reading(){content.innerHTML=`<div class="loadbox"><div class="loader"></div><h2>Reading your syllabus…</h2><p>${app.file&&/^image\//.test(app.file.type)?'Scanning image text with OCR. This can take a few moments.':'Extracting chapters and topics from your document.'}</p></div>`}
async function beginReading(){if(!app.file)return;go(3);try{app.rawText=await extractText(app.file);app.chapters=buildChapters(app.rawText);setTimeout(()=>go(4),400)}catch(e){content.innerHTML=`<h2>We couldn't read that file.</h2><p>${esc(e.message||'Try a clearer PDF, DOCX, or image.')}</p><button class="secondary" onclick="go(2)">Choose another file</button>`}}
async function extractText(file){let ext=file.name.split('.').pop().toLowerCase();if(ext==='txt')return file.text();if(ext==='docx'){if(!window.mammoth)throw Error('The DOCX reader is still loading. Please try again.');return(await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()})).value}if(ext==='pdf'){const mod=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs');mod.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs';const pdf=await mod.getDocument({data:await file.arrayBuffer()}).promise;let t='';for(let n=1;n<=pdf.numPages;n++){let page=await pdf.getPage(n),parts=await page.getTextContent();t+=parts.items.map(x=>x.str).join(' ')+'\n'}return t}if(/^image\//.test(file.type)){if(!window.Tesseract)throw Error('The image reader is still loading. Please try again.');return(await Tesseract.recognize(file,'eng')).data.text}throw Error('Use PDF, DOCX, TXT, PNG, JPG, or WEBP.')}
function buildChapters(text){let lines=text.replace(/\r/g,'').split('\n').map(x=>x.trim()).filter(Boolean),heads=lines.filter(x=>/^(unit|module|chapter)\s*[ivx\d]+|^\d+\s*[.:\-]/i.test(x)),chapters=heads.map((x,i)=>({name:x.replace(/^(unit|module|chapter)\s*[ivx\d]+\s*[:.\-]?\s*/i,'').trim()||`Chapter ${i+1}`,topics:[]}));if(!chapters.length)chapters=[{name:'Extracted course topics',topics:[]}];let active=0;lines.forEach(x=>{let h=heads.indexOf(x);if(h>=0){active=Math.min(h,chapters.length-1);return}chapters[active].topics.push(...x.split(/[,;•|]/).map(y=>y.trim()).filter(y=>y.length>3&&y.length<70))});const fallback=['Introduction and fundamentals','Core concepts','Practical applications','Algorithms and methods','Implementation techniques'];chapters.forEach((c,i)=>{c.topics=[...new Set(c.topics)].filter(x=>!/^(semester|course|code|credits|hours)/i.test(x)).slice(0,12);if(!c.topics.length)c.topics=fallback.slice(i,i+4)});return chapters.slice(0,8)}
function chooseChapter(){content.innerHTML=`<h2>Choose a chapter.</h2><p>We found <b>${app.chapters.length} chapter${app.chapters.length!==1?'s':''}</b> in ${esc(app.file.name)}.</p><div class="topic-grid">${app.chapters.map((c,i)=>`<button class="topic chapter-card ${app.chapter===c.name?'selected':''}" onclick="app.chapter=${JSON.stringify(c.name)};render()"><span><b>${esc(c.name)}</b><small>${c.topics.length} topics detected</small></span><span>0${i+1} →</span></button>`).join('')}</div><button class="primary next" onclick="app.chapter?go(5):alert('Choose a chapter first.')">Continue <span>→</span></button>`}
function difficulty(t){return /dynamic|optimization|neural|distributed|advanced|security|complex|recursion/i.test(t)?'Advanced':/tree|graph|hash|database|api|algorithm|network|design/i.test(t)?'Intermediate':'Beginner'}
function chooseTopic(){let c=app.chapters.find(x=>x.name===app.chapter);content.innerHTML=`<h2>Pick a topic to build on.</h2><p>Each topic has an AI-assigned starting level based on its concepts.</p><div class="topic-grid">${c.topics.map(t=>`<button class="topic ${app.topic===t?'selected':''}" onclick="app.topic=${JSON.stringify(t)};render()">${esc(t)}<small>${difficulty(t)}</small></button>`).join('')}</div><button class="primary next" onclick="app.topic?go(6):alert('Choose a topic first.')">Continue <span>→</span></button>`}
function chooseInterest(){let a=['Web Development','Artificial Intelligence','Gaming','Healthcare','Finance','Mobile Apps'];content.innerHTML=`<h2>What are you interested in?</h2><p>We’ll shape the ideas around the field you want to explore.</p><div class="choice-grid">${a.map(x=>`<button class="choice ${app.interest===x?'selected':''}" onclick="app.interest=${JSON.stringify(x)};render()">${x}</button>`).join('')}</div><button class="primary next" onclick="app.interest?go(7):alert('Choose an area of interest first.')">Continue <span>→</span></button>`}
function chooseLevel(){let a=[['Beginner','A focused build with clear milestones'],['Intermediate','A portfolio-ready feature set'],['Advanced','A deeper technical challenge']];content.innerHTML=`<h2>Choose your project level.</h2><p>You can pick a level different from the topic’s suggested difficulty.</p><div class="choice-grid">${a.map(([x,s])=>`<button class="choice ${app.level===x?'selected':''}" onclick="app.level='${x}';render()">${x}<small>${s}</small></button>`).join('')}</div><button class="primary next" onclick="app.level?go(8):alert('Choose a project level first.')">Generate ideas <span>✦</span></button>`}
function generating(){app.projects=projectIdeas();content.innerHTML=`<div class="loadbox"><div class="loader"></div><h2>Creating personalized ideas…</h2><p>Combining ${esc(app.topic)}, ${esc(app.interest)}, and a ${esc(app.level)} scope.</p></div>`;setTimeout(()=>go(9),800)}
function projectIdeas(){let stacks={'Web Development':['React','Node.js','Express','MongoDB'],'Artificial Intelligence':['Python','FastAPI','scikit-learn','SQLite'],Gaming:['Unity','C#','Firebase','A* Pathfinding'],Healthcare:['React','Node.js','MongoDB','Chart.js'],Finance:['React','Node.js','PostgreSQL','Chart.js'],'Mobile Apps':['React Native','Expo','Firebase','REST API']}[app.interest],roots={'Web Development':['Smart Campus','StudyFlow','Concept Explorer'],'Artificial Intelligence':['Predictive','Intelligent','Adaptive'],Gaming:['Quest','Arcade','Puzzle'],Healthcare:['Care','Wellness','Health'],Finance:['Budget','Finance','Market'],'Mobile Apps':['Pocket','Campus','Learn']}[app.interest],nouns=['Navigator','Assistant','Lab'];return roots.map((r,i)=>({title:`${r} ${nouns[i]}`,description:`Design a ${app.level.toLowerCase()} ${app.interest.toLowerCase()} project that turns ${app.topic.toLowerCase()} into a practical, useful experience.`,application:`A ${app.interest} solution for students and campus communities.`,stack:stacks}))}
function saveIdeas(){content.innerHTML=`<h2>Your project ideas.</h2><div class="result-summary">${esc(app.chapter)} · ${esc(app.topic)} · ${esc(app.interest)} · ${esc(app.level)}</div>${app.projects.map((p,i)=>`<article class="recommendation"><div class="meta">0${i+1} · ${i===0?'BEST MATCH':'ALTERNATIVE IDEA'}</div><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p><h4>Real-world application</h4><p>${esc(p.application)}</p><div class="stack">${p.stack.map(x=>`<span>${esc(x)}</span>`).join('')}<span>${esc(app.topic)}</span></div></article>`).join('')}<div class="project-actions"><button class="primary" onclick="saveProject()">Save my ideas <span>♡</span></button><button class="secondary" onclick="go(10)">Continue to export →</button></div><p class="save-note" id="saveNote"></p>`}
function saveProject(){let saved=JSON.parse(localStorage.getItem('s2p_projects')||'[]');saved.unshift({date:new Date().toISOString(),topic:app.topic,interest:app.interest,projects:app.projects});localStorage.setItem('s2p_projects',JSON.stringify(saved.slice(0,20)));document.getElementById('saveNote').textContent='Saved to this browser. You can return to these ideas later.'}
function exportIdeas(){content.innerHTML=`<h2>Take your ideas with you.</h2><p>Your recommendations are ready for a mentor discussion, project review, or your own reference.</p><div class="recommendation"><div class="meta">PROJECT BRIEF</div><h3>${esc(app.projects[0].title)}</h3><p>Includes all ${app.projects.length} ideas, real-world applications, and technology-stack recommendations.</p></div><button class="primary export" onclick="downloadPDF()">Download project ideas PDF <span>↓</span></button><button class="secondary" onclick="window.print()">Print this page</button><p class="save-note">You’ve completed all 10 steps. Great start, ${esc(app.user.name)}.</p>`}
function downloadPDF(){if(!window.jspdf){alert('The PDF generator is still loading. Please try again.');return}let{jsPDF}=window.jspdf,doc=new jsPDF(),y=20,line=(t,s=11)=>{doc.setFontSize(s);let l=doc.splitTextToSize(t,170);doc.text(l,20,y);y+=l.length*(s*.55)+5;if(y>270){doc.addPage();y=20}};doc.setFontSize(20);doc.text('Syllabus2Project — Project Ideas',20,y);y+=15;line(`Student: ${app.user.name}`);line(`Topic: ${app.chapter} / ${app.topic}`);line(`Interest: ${app.interest} · Level: ${app.level}`);app.projects.forEach((p,i)=>{y+=4;line(`${i+1}. ${p.title}`,15);line(p.description);line(`Real-world application: ${p.application}`);line(`Tech stack: ${p.stack.join(', ')}, ${app.topic}`)});doc.save(`${app.topic.replace(/[^a-z0-9]/gi,'-').toLowerCase()}-project-ideas.pdf`)}
